# Generated by Django 3.2.8 on 2021-10-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_auto_20211030_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
